### ISSUE TITLE
对于继承的实体对象不能识别

### ISSUE THREAD

**Issue by dengsilinming** [yeecode/ObjectLogger#1]
我在使用的时候发现如果实体类有继承的情况下，就算在父类中打了LogDescription标签也没有用，这算是一个bug还是啥，有解决方案么？

**Comment by yeecode** [comment]
你好，确实如此。这是低版本中的一个待解决问题。

可以使用最新版本来实现。具体操作如下：
1、使用新的jar包
```
<dependency>
  <groupId>com.github.yeecode.objectLogger</groupId>
  <artifactId>ObjectLoggerClient</artifactId>
  <version>2.3.0</version>
</dependency>
```
2、因为2.x.x以上版本进行了比较大的重构，因此需要到`/ObjectLogger/server/target`下下载新的后端jar包。
3、2.x.x以上版本的注解也发生了一点变化，LogDescription修改为了LogTag，但是大同小异。具体可参考说明文档。
