### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by dengsilinming** [yeecode/ObjectLogger#2]
com.github.yeecode.objectLogger.client.task.SendLogForObjectTask.run(SendLogForObjectTask.java:63)

if ((fieldWrapper.isWithLogTag() || "true".equals(this.objectLoggerConfigBean.getAutoLog())) && !fieldWrapper.getOldValue().equals(fieldWrapper.getNewValue())) {

如果fieldWrapper.getOldValue()这个为null会有问题

**Comment by yeecode** [comment]
好的，谢谢。
新的版本已经修复了这个问题
