### ISSUE TITLE
对于集群方案

### ISSUE THREAD

**Issue by zxcvbnmzsedr** [yeecode/ObjectLogger#8]
目前server只能够配置单节点，在分布式或者集群环境中该如何使用？

**Comment by yeecode** [comment]
这个可以后续升级，不是当前的主要工作。
目前已经可以通过反向代理等实现多点部署。
在单点部署的情况下，目前也可以支持5应用记录的百万级日志信息的查询。

**Comment by zxcvbnmzsedr** [comment]
单表百万级么？

**Comment by yeecode** [comment]
对的，现在是单表100万多，暂时还没考虑拆分。该表是单独部署在一台机器上的。
另外，log server是部署了两个节点，在两台机器上。
因为多个业务应用之间没啥关联，后期按照业务应用直接拆表也很方便。
